stages:
  - test

unit-test:
  image: python:3.11
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key:
      files:
        - pyproject.toml
    paths:
      - .cache/pip
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install -e .
  script:
    - make test
